services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $rootDir: '%kernel.project_dir%'
      $translationPath: '%translator.default_path%'

  CavernBay\TranslationBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Exception,Model,CavernBayTranslationBundle.php}'

imports:
  - { resource: commands.yml }
