services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $rootDir: '%kernel.project_dir%'
      $translationPath: '%translator.default_path%'

  Kilik\TranslationBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Exception,Model,KilikTranslationBundle.php}'

  kilik.translation.services.load_translation_service: '@Kilik\TranslationBundle\Services\LoadTranslationService'

imports:
  - { resource: commands.yml }
